meta:
- desc: |
   install ceph/mimic latest
tasks:
- install:
    branch: mimic #tag: v13.2.8
    exclude_packages:
      - librados3
      - ceph-mgr-dashboard
      - ceph-mgr-diskprediction-local
      - ceph-mgr-diskprediction-cloud
      - ceph-mgr-rook
      - ceph-mgr-cephadm
      - cephadm
    extra_packages: ['librados2']
- print: "**** done installing mimic"
- ceph:
    mon_bind_addrvec: false
    mon_bind_msgr2: false
    log-whitelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
        ms bind msgr2: false
- exec:
    osd.0:
      - ceph osd require-osd-release mimic
      - ceph osd set-require-min-compat-client mimic
- print: "**** done ceph"
